Vagrant.configure("2") do |config|
	# https://app.vagrantup.com/ubuntu/boxes/trusty64
	# http://cloud-images.ubuntu.com/trusty/
	# Ubuntu Server 14.04 LTS (Trusty Tahr) Daily Builds
	config.vm.box = "ubuntu/trusty64"
	
	config.vm.box_version = "20190429.0.1"
	
	config.vm.provider :virtualbox do |vb|
		vb.gui = true
		vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
		vb.customize ["modifyvm", :id, "--cpus", "2"]
		vb.customize ["modifyvm", :id, "--draganddrop", "bidirectional"]
		vb.customize ["modifyvm", :id, "--memory", "8192"]
		vb.customize ["modifyvm", :id, "--vram", "256"]
		
		vb.customize 'post-boot', ["controlvm", :id, "setvideomodehint", "1440", "900", "32"]
	end
	
	# setup the shared folders
	config.vm.synced_folder "./backup", "/vagrant/backup", id: "backup"
	config.vm.synced_folder "./../tools", "/vagrant/tools", id: "tools"
	config.vm.synced_folder "./../../licenses", "/vagrant/licenses", id: "licenses"
	config.vm.synced_folder "./logs", "/vagrant/logs", id: "logs"
	config.vm.synced_folder "./screenshots", "/vagrant/screenshots", id: "screenshots"
	
	# update
	config.vm.provision :shell, path: "./../scripts/update.sh"
	
	# install virtual box guest tools
	config.vm.provision :shell, path: "./../scripts/install-vb-guest-tools.sh"
	
	# install gui
	config.vm.provision :shell, path: "./../scripts/install-gui.sh"
	
	# install gnome terminal
	config.vm.provision :shell, path: "./../scripts/install-gnome-terminal.sh"
	
	# reload - must have https://github.com/aidanns/vagrant-reload/ - vagrant plugin install vagrant-reload
	config.vm.provision :reload
	
	# update
	config.vm.provision :shell, path: "./../scripts/update.sh"
	
	# install java 8
	config.vm.provision :shell, path: "./../scripts/install-java.sh", args: ["8", "14.04"]
	
	# reload - must have https://github.com/aidanns/vagrant-reload/ - vagrant plugin install vagrant-reload
	config.vm.provision :reload
	
	# install postgre sql 9.4 database and client
	config.vm.provision :shell, path: "./../scripts/install-postgresql.sh", args: ["9.4", "14.04"]
	
	# download pentaho tools
	config.vm.provision :shell, path: "./../scripts/download-pentaho-tools.sh", args: ["7.1"]
	
	# download the jar dependencies
	config.vm.provision :shell, path: "./../scripts/get-jar-dependencies.sh", run: "always"
end
